from typing import Protocol, Any, Sequence
from tinytorch.parameter import Parameter
import numpy as np


class _ModuleProtocol(Protocol):
  def forward(self, *args: Any, **kwargs: Any) -> Any: ...
  def backward(self, grad_out: np.ndarray) -> np.ndarray: ...
  def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
  def parameters(self) -> Sequence[Parameter]: ...


class SingleInputModuleProtocol(_ModuleProtocol, Protocol):
  def forward(self, x: np.ndarray) -> np.ndarray: ...
  def __call__(self, x: np.ndarray) -> np.ndarray: ...


class CriterionModuleProtocol(_ModuleProtocol, Protocol):
  def forward(self, _pred: np.ndarray, _truth: np.ndarray) -> np.ndarray: ...
  def __call__(self, _pred: np.ndarray, _truth: np.ndarray) -> np.ndarray: ...
