from typing import Protocol, Any, Sequence
from base.parameter import Parameter
import numpy as np


class _ModuleProtocol(Protocol):
  def forward(self, *args: Any, **kwargs: Any) -> Any: ...
  def backward(self, *args: Any, **kwargs: Any) -> Any: ...
  def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
  def zero_grad(self) -> None: ...
  def parameters(self) -> Sequence[Parameter]: ...


class SingleInputModule(_ModuleProtocol, Protocol):
  def forward(self, x: np.ndarray) -> np.ndarray: ...
  def backward(self, grad_out: np.ndarray) -> np.ndarray: ...
  def __call__(self, x: np.ndarray) -> np.ndarray: ...


class LossModule(_ModuleProtocol, Protocol):
  def forward(self, _prediction: np.ndarray, _ground_truth: np.ndarray) -> np.floating: ...
  def backward(self, grad_out: np.floating) -> np.ndarray: ...
  def __call__(self, _prediction: np.ndarray, _ground_truth: np.ndarray) -> np.floating: ...
